"""schema update

Revision ID: 57efbf9514a8
Revises: f26371892d5f
Create Date: 2026-01-21 21:34:33.541223

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes

import pgvector.sqlalchemy

# revision identifiers, used by Alembic.
revision = '57efbf9514a8'
down_revision = 'f26371892d5f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('product', 'style_embedding',
                    existing_type=pgvector.sqlalchemy.vector.VECTOR(dim=768),
                    type_=pgvector.sqlalchemy.vector.VECTOR(dim=512),
                    existing_nullable=True)
    op.alter_column('product', 'complementary_embedding',
                    existing_type=pgvector.sqlalchemy.vector.VECTOR(dim=768),
                    type_=pgvector.sqlalchemy.vector.VECTOR(dim=512),
                    existing_nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('product', 'complementary_embedding',
                    existing_type=pgvector.sqlalchemy.vector.VECTOR(dim=512),
                    type_=pgvector.sqlalchemy.vector.VECTOR(dim=768),
                    existing_nullable=True)
    op.alter_column('product', 'style_embedding',
                    existing_type=pgvector.sqlalchemy.vector.VECTOR(dim=512),
                    type_=pgvector.sqlalchemy.vector.VECTOR(dim=768),
                    existing_nullable=True)
    # ### end Alembic commands ###
