"""User and product schema updated

Revision ID: 88b6d3a26c7a
Revises: 
Create Date: 2026-01-20 20:51:00.858119

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes
import pgvector.sqlalchemy


# revision identifiers, used by Alembic.
revision = '88b6d3a26c7a'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("CREATE EXTENSION IF NOT EXISTS vector")
    op.create_table('product',
                    sa.Column(
                        'name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
                    sa.Column(
                        'brand', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
                    sa.Column('master_category',
                              sqlmodel.sql.sqltypes.AutoString(), nullable=False),
                    sa.Column('sub_category', sqlmodel.sql.sqltypes.AutoString(),
                              nullable=False),
                    sa.Column('article_type', sqlmodel.sql.sqltypes.AutoString(),
                              nullable=False),
                    sa.Column(
                        'gender', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
                    sa.Column('mrp', sa.Float(), nullable=False),
                    sa.Column('price', sa.Float(), nullable=False),
                    sa.Column('primary_colour',
                              sqlmodel.sql.sqltypes.AutoString(), nullable=False),
                    sa.Column(
                        'fit', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
                    sa.Column(
                        'material', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
                    sa.Column(
                        'season', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
                    sa.Column('id', sa.Uuid(), nullable=False),
                    sa.Column('rating', sa.Float(), nullable=False),
                    sa.Column('rating_count', sa.Integer(), nullable=False),
                    sa.Column('is_fast_fashion', sa.Boolean(), nullable=False),
                    sa.Column('catalog_date', sa.Integer(), nullable=False),
                    sa.Column('occasion_tags', sa.JSON(), nullable=True),
                    sa.Column('formality_score', sa.Float(), nullable=False),
                    sa.Column('style_archetype',
                              sqlmodel.sql.sqltypes.AutoString(), nullable=True),
                    sa.Column('images', sa.JSON(), nullable=True),
                    sa.Column('landing_page_url',
                              sqlmodel.sql.sqltypes.AutoString(), nullable=False),
                    sa.Column('style_embedding', pgvector.sqlalchemy.vector.VECTOR(
                        dim=768), nullable=True),
                    sa.Column('complementary_embedding',
                              pgvector.sqlalchemy.vector.VECTOR(dim=768), nullable=True),
                    sa.Column('semantic_embedding', pgvector.sqlalchemy.vector.VECTOR(
                        dim=384), nullable=True),
                    sa.PrimaryKeyConstraint('id')
                    )
    op.create_index(op.f('ix_product_brand'),
                    'product', ['brand'], unique=False)
    op.create_index(op.f('ix_product_name'), 'product', ['name'], unique=False)
    op.create_table('user',
                    sa.Column('email', sqlmodel.sql.sqltypes.AutoString(
                        length=255), nullable=False),
                    sa.Column(
                        'full_name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
                    sa.Column(
                        'gender', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
                    sa.Column(
                        'body_type', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
                    sa.Column(
                        'skin_tone', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
                    sa.Column(
                        'height_cm', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
                    sa.Column('id', sa.Uuid(), nullable=False),
                    sa.Column('hashed_password',
                              sqlmodel.sql.sqltypes.AutoString(), nullable=False),
                    sa.Column('created_at', sa.DateTime(), nullable=False),
                    sa.Column('style_scores', sa.JSON(), nullable=True),
                    sa.Column('spending_profile', sa.JSON(), nullable=True),
                    sa.Column('price_sensitivity_score',
                              sa.Float(), nullable=False),
                    sa.Column('style_embedding', pgvector.sqlalchemy.vector.VECTOR(
                        dim=768), nullable=True),
                    sa.Column('return_rate', sa.Float(), nullable=False),
                    sa.Column('last_active', sa.DateTime(), nullable=False),
                    sa.PrimaryKeyConstraint('id')
                    )
    op.create_index(op.f('ix_user_email'), 'user', ['email'], unique=True)
    op.create_table('inventory',
                    sa.Column('id', sa.Uuid(), nullable=False),
                    sa.Column('product_id', sa.Uuid(), nullable=False),
                    sa.Column('sku_id', sa.Integer(), nullable=False),
                    sa.Column(
                        'size', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
                    sa.Column('stock_count', sa.Integer(), nullable=False),
                    sa.Column('available', sa.Boolean(), nullable=False),
                    sa.ForeignKeyConstraint(['product_id'], ['product.id'], ),
                    sa.PrimaryKeyConstraint('id')
                    )
    op.create_index(op.f('ix_inventory_sku_id'),
                    'inventory', ['sku_id'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_inventory_sku_id'), table_name='inventory')
    op.drop_table('inventory')
    op.drop_index(op.f('ix_user_email'), table_name='user')
    op.drop_table('user')
    op.drop_index(op.f('ix_product_name'), table_name='product')
    op.drop_index(op.f('ix_product_brand'), table_name='product')
    op.drop_table('product')
    # ### end Alembic commands ###
