"""schema update

Revision ID: f26371892d5f
Revises: 88b6d3a26c7a
Create Date: 2026-01-21 19:37:15.998677

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision = 'f26371892d5f'
down_revision = '88b6d3a26c7a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('productcompatibility',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('base_product_id', sa.Uuid(), nullable=False),
    sa.Column('recommended_product_id', sa.Uuid(), nullable=False),
    sa.Column('compatibility_score', sa.Float(), nullable=False),
    sa.Column('occasion_context', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.ForeignKeyConstraint(['base_product_id'], ['product.id'], ),
    sa.ForeignKeyConstraint(['recommended_product_id'], ['product.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_productcompatibility_base_product_id'), 'productcompatibility', ['base_product_id'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_productcompatibility_base_product_id'), table_name='productcompatibility')
    op.drop_table('productcompatibility')
    # ### end Alembic commands ###
